/* ================================================================ WORDS
   270 high-frequency words, ten a day, grouped so each day's ten belong together.
   Each: [Spanish, English, example sentence, its English].  Nouns carry their article
   so the gender is learned with the word (Essential Grammar ch. 2; MSG ch. 2).          */
var WORD_SETS = [
 "First words", "People", "Question words", "The little words", "More little words", "When",
 "Family", "At home", "Food and drink", "Describing", "Ten verbs you need first",
 "Ten more everyday verbs", "Useful little words", "Numbers 1–10", "Numbers and amounts", "Time", "The week",
 "Places", "Getting around", "Body and health", "Feelings", "Doing things",
 "More doing", "Money and shopping", "Weather and nature", "How much, how fast", "Faith and life"
];
var WORDS = [
 /* 1 First words */
 ["hola","hello","Hola, ¿cómo estás?","Hello, how are you?"],
 ["adiós","goodbye","Adiós, hasta mañana.","Goodbye, see you tomorrow."],
 ["sí","yes","Sí, claro.","Yes, of course."],
 ["no","no / not","No, gracias.","No, thank you."],
 ["por favor","please","Un café, por favor.","A coffee, please."],
 ["gracias","thank you","Muchas gracias por todo.","Thank you very much for everything."],
 ["de nada","you’re welcome","—Gracias. —De nada.","“Thanks.” “You’re welcome.”"],
 ["perdón","sorry / excuse me","Perdón, no entiendo.","Sorry, I don’t understand."],
 ["bien","well / fine","Estoy bien, gracias.","I’m fine, thanks."],
 ["muy","very","La comida está muy buena.","The food is very good."],
 /* 2 People */
 ["yo","I","Yo soy de Ohio.","I am from Ohio."],
 ["tú","you (friendly)","¿Tú hablas inglés?","Do you speak English?"],
 ["usted","you (polite)","¿Usted es el doctor?","Are you the doctor?"],
 ["él","he","Él trabaja aquí.","He works here."],
 ["ella","she","Ella es mi hermana.","She is my sister."],
 ["nosotros","we","Nosotros vamos a la iglesia.","We go to church."],
 ["ellos","they","Ellos viven en México.","They live in Mexico."],
 ["la persona","person","Es una persona muy amable.","She is a very kind person."],
 ["el amigo","friend","Mi amigo se llama Carlos.","My friend’s name is Carlos."],
 ["la gente","people","La gente aquí es muy simpática.","The people here are very nice."],
 /* 3 Question words */
 ["qué","what","¿Qué quieres comer?","What do you want to eat?"],
 ["quién","who","¿Quién es ella?","Who is she?"],
 ["dónde","where","¿Dónde está el baño?","Where is the bathroom?"],
 ["cuándo","when","¿Cuándo es la fiesta?","When is the party?"],
 ["cómo","how","¿Cómo se dice “book” en español?","How do you say “book” in Spanish?"],
 ["por qué","why","¿Por qué estás triste?","Why are you sad?"],
 ["porque","because","Estoy cansada porque trabajé mucho.","I’m tired because I worked a lot."],
 ["cuánto","how much","¿Cuánto cuesta?","How much does it cost?"],
 ["cuál","which / what","¿Cuál es tu número?","What is your number?"],
 ["si","if","Si tienes tiempo, llámame.","If you have time, call me."],
 /* 4 The little words */
 ["y","and","Pan y café.","Bread and coffee."],
 ["o","or","¿Té o café?","Tea or coffee?"],
 ["pero","but","Quiero ir, pero no puedo.","I want to go, but I can’t."],
 ["con","with","Voy con mi mamá.","I’m going with my mom."],
 ["sin","without","Un café sin azúcar.","A coffee without sugar."],
 ["para","for / in order to","Es un regalo para ti.","It’s a gift for you."],
 ["de","of / from","Soy de Texas.","I’m from Texas."],
 ["en","in / on / at","Estoy en casa.","I’m at home."],
 ["a","to / at","Vamos a la playa.","Let’s go to the beach."],
 ["el / la","the","El libro y la mesa.","The book and the table."],
 /* 5 More little words (the most frequent words in Spanish: RAE / Davies frequency lists) */
 ["que","that","Dice que viene mañana.","She says that she’s coming tomorrow."],
 ["por","for / through / by","Gracias por la ayuda.","Thanks for the help."],
 ["su","his / her / their / your","Su casa es muy bonita.","Her house is very pretty."],
 ["este","this","Este libro es mío.","This book is mine."],
 ["otro","other / another","¿Quieres otro café?","Do you want another coffee?"],
 ["cada","each / every","Voy cada semana.","I go every week."],
 ["hay","there is / there are","Hay mucha gente aquí.","There are a lot of people here."],
 ["entre","between","Está entre el banco y la tienda.","It’s between the bank and the store."],
 ["desde","since / from","Trabajo aquí desde enero.","I’ve worked here since January."],
 ["hasta","until","Trabajo hasta las cinco.","I work until five."],
 /* 5 When */
 ["hoy","today","Hoy tengo clase.","Today I have class."],
 ["mañana","tomorrow","Nos vemos mañana.","See you tomorrow."],
 ["ayer","yesterday","Ayer fui al mercado.","Yesterday I went to the market."],
 ["ahora","now","Ahora no puedo hablar.","I can’t talk now."],
 ["siempre","always","Siempre llego temprano.","I always arrive early."],
 ["nunca","never","Nunca como carne.","I never eat meat."],
 ["a veces","sometimes","A veces cocino en casa.","Sometimes I cook at home."],
 ["ya","already","Ya terminé.","I already finished."],
 ["todavía","still / yet","Todavía no sé.","I don’t know yet."],
 ["después","after / later","Te llamo después.","I’ll call you later."],
 /* 6 Family */
 ["la familia","family","Mi familia es grande.","My family is big."],
 ["la madre","mother","Mi madre cocina muy bien.","My mother cooks very well."],
 ["el padre","father","Mi padre es de Colombia.","My father is from Colombia."],
 ["el hijo","son","Su hijo tiene cinco años.","Her son is five years old."],
 ["la hija","daughter","Tengo una hija.","I have a daughter."],
 ["el hermano","brother","Mi hermano vive lejos.","My brother lives far away."],
 ["la hermana","sister","¿Tienes hermanas?","Do you have sisters?"],
 ["el esposo","husband","Mi esposo trabaja mucho.","My husband works a lot."],
 ["la esposa","wife","Su esposa es maestra.","His wife is a teacher."],
 ["los padres","parents","Mis padres están en casa.","My parents are at home."],
 /* 7 At home */
 ["la casa","house / home","Bienvenidos a mi casa.","Welcome to my home."],
 ["la puerta","door","Cierra la puerta, por favor.","Close the door, please."],
 ["la cocina","kitchen","Estoy en la cocina.","I’m in the kitchen."],
 ["el cuarto","room / bedroom","Mi cuarto es pequeño.","My room is small."],
 ["la cama","bed","Me voy a la cama.","I’m going to bed."],
 ["la mesa","table","La comida está en la mesa.","The food is on the table."],
 ["la silla","chair","Toma una silla.","Take a chair."],
 ["el baño","bathroom","El baño está al fondo.","The bathroom is at the back."],
 ["la ventana","window","Abre la ventana.","Open the window."],
 ["la llave","key","No encuentro mis llaves.","I can’t find my keys."],
 /* 8 Food and drink */
 ["la comida","food / meal","La comida está lista.","The food is ready."],
 ["el agua","water","Un vaso de agua, por favor.","A glass of water, please."],
 ["el café","coffee","Tomo café todas las mañanas.","I drink coffee every morning."],
 ["el pan","bread","El pan está fresco.","The bread is fresh."],
 ["la leche","milk","¿Tienes leche?","Do you have milk?"],
 ["la carne","meat","No como carne roja.","I don’t eat red meat."],
 ["el pollo","chicken","Quiero arroz con pollo.","I want rice with chicken."],
 ["la fruta","fruit","Me gusta la fruta.","I like fruit."],
 ["el desayuno","breakfast","El desayuno es a las ocho.","Breakfast is at eight."],
 ["la cena","dinner","¿Qué hay para la cena?","What’s for dinner?"],
 /* 9 Describing */
 ["grande","big","Es una ciudad grande.","It’s a big city."],
 ["pequeño","small","Tengo un perro pequeño.","I have a small dog."],
 ["bueno","good","Es un buen libro.","It’s a good book."],
 ["malo","bad","Hace mal tiempo.","The weather is bad."],
 ["nuevo","new","Tengo un teléfono nuevo.","I have a new phone."],
 ["viejo","old","Es un carro viejo.","It’s an old car."],
 ["bonito","pretty","¡Qué bonito día!","What a pretty day!"],
 ["feliz","happy","Estoy muy feliz.","I’m very happy."],
 ["cansado","tired","Estoy cansada hoy.","I’m tired today."],
 ["difícil","difficult","El examen fue difícil.","The exam was difficult."],
 /* 10 Ten verbs you need first */
 ["ser","to be (what it is)","Soy estudiante.","I am a student."],
 ["estar","to be (how or where)","Estoy en clase.","I’m in class."],
 ["tener","to have","Tengo dos hermanos.","I have two brothers."],
 ["ir","to go","Voy a la tienda.","I’m going to the store."],
 ["hacer","to do / to make","¿Qué haces?","What are you doing?"],
 ["poder","to be able to, can","¿Puedes ayudarme?","Can you help me?"],
 ["querer","to want / to love","Quiero aprender español.","I want to learn Spanish."],
 ["decir","to say / to tell","¿Qué dices?","What are you saying?"],
 ["saber","to know (a fact)","No sé.","I don’t know."],
 ["venir","to come","¿Vienes conmigo?","Are you coming with me?"],
 /* 11 Ten more everyday verbs */
 ["hablar","to speak","Hablo un poco de español.","I speak a little Spanish."],
 ["comer","to eat","¿Quieres comer algo?","Do you want to eat something?"],
 ["vivir","to live","Vivo en Cedarville.","I live in Cedarville."],
 ["trabajar","to work","Trabajo los sábados.","I work on Saturdays."],
 ["necesitar","to need","Necesito ayuda.","I need help."],
 ["gustar","to like (to be pleasing)","Me gusta el café.","I like coffee."],
 ["llegar","to arrive","Llego a las cinco.","I arrive at five."],
 ["salir","to go out / to leave","Salgo de casa a las siete.","I leave home at seven."],
 ["ver","to see / to watch","Vamos a ver una película.","We’re going to watch a movie."],
 ["dar","to give","Te doy mi número.","I’ll give you my number."],
 /* Useful little words */
 ["también","also / too","Yo también.","Me too."],
 ["así","like this / so","Se hace así.","It’s done like this."],
 ["tan","so","¡Es tan bonito!","It’s so pretty!"],
 ["algo","something","¿Quieres algo de tomar?","Do you want something to drink?"],
 ["nada","nothing","No tengo nada.","I have nothing."],
 ["alguien","someone","¿Hay alguien en casa?","Is anyone home?"],
 ["nadie","nobody","No hay nadie.","There’s nobody here."],
 ["conmigo","with me","¿Quieres venir conmigo?","Do you want to come with me?"],
 ["contigo","with you","Voy contigo.","I’ll go with you."],
 ["sobre","about / on","Hablamos sobre la clase.","We talked about the class."],
 /* 12 Numbers 1–10 */
 ["uno","one","Solo uno, por favor.","Just one, please."],
 ["dos","two","Tengo dos hijos.","I have two children."],
 ["tres","three","Son las tres.","It’s three o’clock."],
 ["cuatro","four","Somos cuatro.","There are four of us."],
 ["cinco","five","Cinco minutos, por favor.","Five minutes, please."],
 ["seis","six","La clase es a las seis.","Class is at six."],
 ["siete","seven","La semana tiene siete días.","The week has seven days."],
 ["ocho","eight","Trabajo ocho horas.","I work eight hours."],
 ["nueve","nine","Llego a las nueve.","I arrive at nine."],
 ["diez","ten","Cuesta diez dólares.","It costs ten dollars."],
 /* 13 Numbers and amounts */
 ["veinte","twenty","Tengo veinte años.","I’m twenty years old."],
 ["treinta","thirty","Treinta minutos más.","Thirty more minutes."],
 ["cien","one hundred","Cien por ciento.","One hundred percent."],
 ["mil","a thousand","Mil gracias.","A thousand thanks."],
 ["primero","first","Es mi primer día.","It’s my first day."],
 ["el número","number","¿Cuál es tu número de teléfono?","What’s your phone number?"],
 ["la mitad","half","La mitad es para ti.","Half is for you."],
 ["más","more","Quiero más café.","I want more coffee."],
 ["menos","less","Quiero menos azúcar.","I want less sugar."],
 ["todo","all / everything","Todo está bien.","Everything is fine."],
 /* 14 Time */
 ["el día","day","¡Buen día!","Good morning!"],
 ["la semana","week","Nos vemos la próxima semana.","See you next week."],
 ["el mes","month","Voy a México el próximo mes.","I’m going to Mexico next month."],
 ["el año","year","Feliz año nuevo.","Happy New Year."],
 ["la hora","hour","¿Qué hora es?","What time is it?"],
 ["el minuto","minute","Espera un minuto.","Wait a minute."],
 ["la mañana","morning","Estudio por la mañana.","I study in the morning."],
 ["la tarde","afternoon","Buenas tardes.","Good afternoon."],
 ["la noche","night","Buenas noches.","Good night."],
 ["el fin de semana","weekend","¿Qué haces el fin de semana?","What are you doing this weekend?"],
 /* 15 The week */
 ["lunes","Monday","El lunes tengo examen.","On Monday I have an exam."],
 ["martes","Tuesday","Los martes voy al gimnasio.","On Tuesdays I go to the gym."],
 ["miércoles","Wednesday","Hoy es miércoles.","Today is Wednesday."],
 ["jueves","Thursday","Nos vemos el jueves.","See you on Thursday."],
 ["viernes","Friday","¡Por fin es viernes!","It’s Friday at last!"],
 ["sábado","Saturday","El sábado descanso.","On Saturday I rest."],
 ["domingo","Sunday","El domingo voy a la iglesia.","On Sunday I go to church."],
 ["la fecha","date","¿Cuál es la fecha de hoy?","What’s today’s date?"],
 ["el cumpleaños","birthday","¡Feliz cumpleaños!","Happy birthday!"],
 ["la fiesta","party","La fiesta es el sábado.","The party is on Saturday."],
 /* 16 Places */
 ["la ciudad","city","Me gusta esta ciudad.","I like this city."],
 ["la calle","street","Vivo en esta calle.","I live on this street."],
 ["la tienda","store","La tienda está cerrada.","The store is closed."],
 ["el trabajo","work / job","Voy al trabajo en carro.","I go to work by car."],
 ["la escuela","school","Los niños están en la escuela.","The children are at school."],
 ["la iglesia","church","La iglesia está cerca.","The church is close by."],
 ["el hospital","hospital","¿Dónde está el hospital?","Where is the hospital?"],
 ["el restaurante","restaurant","Conozco un buen restaurante.","I know a good restaurant."],
 ["el banco","bank","El banco abre a las nueve.","The bank opens at nine."],
 ["el país","country","¿De qué país eres?","What country are you from?"],
 /* 17 Getting around */
 ["el carro","car","Mi carro es azul.","My car is blue."],
 ["el autobús","bus","Tomo el autobús.","I take the bus."],
 ["el aeropuerto","airport","Vamos al aeropuerto.","We’re going to the airport."],
 ["a la izquierda","to the left","Gire a la izquierda.","Turn left."],
 ["a la derecha","to the right","Está a la derecha.","It’s on the right."],
 ["derecho","straight ahead","Siga derecho.","Keep going straight."],
 ["cerca","near","¿Hay un banco cerca?","Is there a bank nearby?"],
 ["lejos","far","No está lejos.","It isn’t far."],
 ["la esquina","corner","Está en la esquina.","It’s on the corner."],
 ["el mapa","map","¿Me lo enseña en el mapa?","Can you show me on the map?"],
 /* 18 Body and health */
 ["la cabeza","head","Me duele la cabeza.","My head hurts."],
 ["el estómago","stomach","Me duele el estómago.","My stomach hurts."],
 ["la mano","hand","Lávate las manos.","Wash your hands."],
 ["el pie","foot","Me duele el pie.","My foot hurts."],
 ["los ojos","eyes","Tiene los ojos verdes.","She has green eyes."],
 ["el dolor","pain","Tengo mucho dolor.","I’m in a lot of pain."],
 ["enfermo","sick","Mi hijo está enfermo.","My son is sick."],
 ["el médico","doctor","Necesito ver al médico.","I need to see the doctor."],
 ["la medicina","medicine","Toma la medicina con agua.","Take the medicine with water."],
 ["la farmacia","pharmacy","La farmacia está abierta.","The pharmacy is open."],
 /* 19 Feelings */
 ["contento","glad","Estoy contenta con el resultado.","I’m glad about the result."],
 ["triste","sad","Hoy estoy un poco triste.","Today I’m a little sad."],
 ["enojado","angry","Está enojado conmigo.","He’s angry with me."],
 ["preocupado","worried","Estoy preocupada por el examen.","I’m worried about the exam."],
 ["nervioso","nervous","Estoy un poco nerviosa.","I’m a little nervous."],
 ["tranquilo","calm","Tranquila, todo va a estar bien.","Relax, everything will be fine."],
 ["el miedo","fear","Tengo miedo.","I’m afraid."],
 ["sorprendido","surprised","Estoy muy sorprendida.","I’m very surprised."],
 ["aburrido","bored / boring","La película es aburrida.","The movie is boring."],
 ["emocionado","excited","¡Estoy muy emocionada!","I’m so excited!"],
 /* 20 Doing things */
 ["comprar","to buy","Quiero comprar pan.","I want to buy bread."],
 ["pagar","to pay","¿Puedo pagar con tarjeta?","Can I pay by card?"],
 ["buscar","to look for","Busco la estación.","I’m looking for the station."],
 ["encontrar","to find","No encuentro mi teléfono.","I can’t find my phone."],
 ["llamar","to call","Te llamo esta noche.","I’ll call you tonight."],
 ["esperar","to wait / to hope","Espérame aquí.","Wait for me here."],
 ["ayudar","to help","¿Me puedes ayudar?","Can you help me?"],
 ["entender","to understand","No entiendo la pregunta.","I don’t understand the question."],
 ["pensar","to think","Pienso que sí.","I think so."],
 ["creer","to believe","Creo en Dios.","I believe in God."],
 /* 21 More doing */
 ["dormir","to sleep","Duermo ocho horas.","I sleep eight hours."],
 ["pedir","to ask for / to order","Voy a pedir la sopa.","I’m going to order the soup."],
 ["volver","to come back","Vuelvo en cinco minutos.","I’ll be back in five minutes."],
 ["empezar","to begin","La clase empieza a las diez.","Class begins at ten."],
 ["terminar","to finish","Terminé la tarea.","I finished the homework."],
 ["abrir","to open","¿Puedes abrir la puerta?","Can you open the door?"],
 ["cerrar","to close","Cierran a las ocho.","They close at eight."],
 ["escribir","to write","Escríbeme un mensaje.","Write me a message."],
 ["leer","to read","Me gusta leer.","I like to read."],
 ["escuchar","to listen","Escucha esta canción.","Listen to this song."],
 /* 22 Money and shopping */
 ["el dinero","money","No tengo dinero.","I don’t have money."],
 ["la tarjeta","card","¿Aceptan tarjeta?","Do you take cards?"],
 ["el precio","price","¿Cuál es el precio?","What’s the price?"],
 ["caro","expensive","Es muy caro.","It’s very expensive."],
 ["barato","cheap","Este es más barato.","This one is cheaper."],
 ["la cuenta","the check, the bill","La cuenta, por favor.","The check, please."],
 ["el cambio","change","Quédese con el cambio.","Keep the change."],
 ["la bolsa","bag","¿Necesita una bolsa?","Do you need a bag?"],
 ["la ropa","clothes","Voy a comprar ropa.","I’m going to buy clothes."],
 ["la talla","size","¿Tiene una talla más grande?","Do you have a bigger size?"],
 /* 23 Weather and nature */
 ["el tiempo","weather / time","¿Qué tiempo hace?","What’s the weather like?"],
 ["el sol","sun","Hace sol.","It’s sunny."],
 ["la lluvia","rain","Me gusta la lluvia.","I like the rain."],
 ["el calor","heat","Hace mucho calor.","It’s very hot."],
 ["el frío","cold","Hace frío hoy.","It’s cold today."],
 ["el cielo","sky / heaven","El cielo está azul.","The sky is blue."],
 ["el mar","sea","Vamos al mar.","Let’s go to the sea."],
 ["la playa","beach","La playa está llena.","The beach is full."],
 ["la montaña","mountain","Vivimos cerca de las montañas.","We live near the mountains."],
 ["el árbol","tree","Hay un árbol grande en el parque.","There’s a big tree in the park."],
 /* 24 How much, how fast */
 ["mucho","a lot","Te quiero mucho.","I love you very much."],
 ["poco","a little","Hablo un poco de español.","I speak a little Spanish."],
 ["bastante","quite / enough","Es bastante fácil.","It’s quite easy."],
 ["demasiado","too much","Es demasiado caro.","It’s too expensive."],
 ["casi","almost","Casi terminé.","I almost finished."],
 ["solo","only / just","Solo quiero agua.","I just want water."],
 ["otra vez","again","¿Puede repetirlo otra vez?","Can you repeat it again?"],
 ["juntos","together","Vamos juntos.","Let’s go together."],
 ["rápido","fast","Hablas muy rápido.","You speak very fast."],
 ["despacio","slowly","Más despacio, por favor.","More slowly, please."],
 /* 25 Faith and life */
 ["Dios","God","Dios te bendiga.","God bless you."],
 ["la fe","faith","La fe es muy importante para mí.","Faith is very important to me."],
 ["la Biblia","the Bible","Leo la Biblia cada mañana.","I read the Bible every morning."],
 ["orar","to pray","Vamos a orar juntos.","Let’s pray together."],
 ["la oración","prayer","Gracias por tus oraciones.","Thank you for your prayers."],
 ["la vida","life","La vida es bella.","Life is beautiful."],
 ["el amor","love","Dios es amor.","God is love."],
 ["la verdad","truth","Dime la verdad.","Tell me the truth."],
 ["la paz","peace","La paz sea contigo.","Peace be with you."],
 ["la esperanza","hope","Siempre hay esperanza.","There is always hope."]
];
