/* ================================================================ SPEAKING MATERIAL
   SURVIVAL   Modern Spanish Grammar part B: ch. 29 (making social contacts) and ch. 30
              (basic strategies for communication), the phrases that keep a conversation alive.
   BUILDERS   sentence starters that take an infinitive, so one verb becomes many sentences.
   CONNECTORS the words that join ideas (MSG ch. 27 conjunctions, ch. 43, 52; EG ch. 25).
   DIALOGUES  short scenes to role-play: the app speaks one part, you speak the other.   */

var SURVIVAL_GROUPS = [
  {k:"greet",  name:"Hello and goodbye",           src:"MSG 29.1–29.5"},
  {k:"help",   name:"When you don’t understand",   src:"MSG 30.3–30.5"},
  {k:"fill",   name:"Buying time (fillers)",       src:"MSG 30.8"},
  {k:"polite", name:"Being polite",                src:"MSG 64, 66, 68"},
  {k:"react",  name:"Reacting",                    src:"MSG 56, 59, 60"}
];
var SURVIVAL = [
  ["greet","Buenos días.","Good morning."],
  ["greet","Buenas tardes.","Good afternoon."],
  ["greet","¿Cómo estás?","How are you? (friendly)"],
  ["greet","¿Cómo está usted?","How are you? (polite)"],
  ["greet","Muy bien, ¿y tú?","Very well, and you?"],
  ["greet","Me llamo Ana. ¿Y tú?","My name is Ana. And you?"],
  ["greet","Mucho gusto.","Nice to meet you."],
  ["greet","Igualmente.","Likewise."],
  ["greet","Hasta luego.","See you later."],
  ["greet","Que te vaya bien.","Hope it goes well for you."],
  ["help","No entiendo.","I don’t understand."],
  ["help","¿Puede repetir, por favor?","Could you repeat that, please?"],
  ["help","Más despacio, por favor.","More slowly, please."],
  ["help","¿Qué significa “sobremesa”?","What does “sobremesa” mean?"],
  ["help","¿Cómo se dice “to hug” en español?","How do you say “to hug” in Spanish?"],
  ["help","¿Me entiendes?","Do you understand me?"],
  ["help","¿Quieres decir que…?","Do you mean that…?"],
  ["help","Estoy aprendiendo español.","I’m learning Spanish."],
  ["help","¿Cómo se escribe?","How do you spell it?"],
  ["help","Ah, ya entiendo.","Oh, now I understand."],
  ["fill","Bueno…","Well…"],
  ["fill","Pues…","Well… / So…"],
  ["fill","A ver…","Let’s see…"],
  ["fill","Este…","Um…"],
  ["fill","O sea…","I mean…"],
  ["fill","¿Cómo te digo?","How can I put it?"],
  ["fill","Es que…","The thing is…"],
  ["fill","Por cierto…","By the way…"],
  ["polite","¿Me podría ayudar?","Could you help me?"],
  ["polite","Quisiera un café, por favor.","I would like a coffee, please."],
  ["polite","Con permiso.","Excuse me (to get past)."],
  ["polite","Lo siento mucho.","I’m very sorry."],
  ["polite","No pasa nada.","It’s no problem."],
  ["polite","Muchísimas gracias.","Thank you so much."],
  ["polite","Con mucho gusto.","With pleasure."],
  ["react","¡Qué bien!","How great!"],
  ["react","¡No me digas!","No way! (Don’t tell me!)"],
  ["react","¡Qué lástima!","What a shame!"],
  ["react","Claro que sí.","Of course."],
  ["react","Tienes razón.","You’re right."],
  ["react","No estoy de acuerdo.","I don’t agree."],
  ["react","Me da igual.","I don’t mind either way."],
  ["react","¿En serio?","Really?"]
];

/* one starter + an infinitive = a sentence. MSG ch. 21 (modals), 46, 47, 53, 57, 72 */
var BUILDERS = [
  {es:"Quiero…",        en:"I want to…",            ex:[["Quiero comer.","I want to eat."],["Quiero aprender español.","I want to learn Spanish."],["Quiero ir a casa.","I want to go home."]]},
  {es:"Necesito…",      en:"I need to…",            ex:[["Necesito descansar.","I need to rest."],["Necesito hablar contigo.","I need to talk to you."],["Necesito comprar pan.","I need to buy bread."]]},
  {es:"Puedo…",         en:"I can…",                ex:[["Puedo ayudarte.","I can help you."],["¿Puedo pagar con tarjeta?","Can I pay by card?"],["No puedo ir hoy.","I can’t go today."]]},
  {es:"Voy a…",         en:"I’m going to…",         ex:[["Voy a estudiar.","I’m going to study."],["Voy a llamar a mi mamá.","I’m going to call my mom."],["Vamos a comer.","Let’s eat."]]},
  {es:"Tengo que…",     en:"I have to…",            ex:[["Tengo que trabajar.","I have to work."],["Tengo que irme.","I have to go."],["Tenemos que hablar.","We need to talk."]]},
  {es:"Me gusta…",      en:"I like to…",            ex:[["Me gusta leer.","I like to read."],["Me gusta cocinar.","I like to cook."],["No me gusta correr.","I don’t like to run."]]},
  {es:"Me gustaría…",   en:"I would like to…",      ex:[["Me gustaría viajar a España.","I would like to travel to Spain."],["Me gustaría pedir la cuenta.","I’d like to ask for the check."],["¿Te gustaría venir?","Would you like to come?"]]},
  {es:"Acabo de…",      en:"I just (did)…",         ex:[["Acabo de llegar.","I just arrived."],["Acabo de comer.","I just ate."],["Acaba de salir.","She just left."]]},
  {es:"Estoy…-ando",    en:"I am (doing) right now", ex:[["Estoy estudiando.","I’m studying."],["Estoy cocinando.","I’m cooking."],["Estamos esperando.","We’re waiting."]]},
  {es:"Hay que…",       en:"One has to… / We must…", ex:[["Hay que practicar todos los días.","You have to practice every day."],["Hay que tener paciencia.","You have to be patient."],["Hay que salir temprano.","We have to leave early."]]},
  {es:"Sé…",            en:"I know how to…",        ex:[["Sé nadar.","I know how to swim."],["No sé cocinar.","I don’t know how to cook."],["¿Sabes manejar?","Do you know how to drive?"]]},
  {es:"Intento…",       en:"I try to…",             ex:[["Intento hablar más.","I try to speak more."],["Intento dormir ocho horas.","I try to sleep eight hours."],["Intento llegar a tiempo.","I try to arrive on time."]]},
  {es:"Suelo…",         en:"I usually…",            ex:[["Suelo levantarme temprano.","I usually get up early."],["Suelo leer por la noche.","I usually read at night."],["¿Qué sueles hacer los domingos?","What do you usually do on Sundays?"]]},
  {es:"Vuelvo a…",      en:"I (do it) again",       ex:[["Vuelvo a intentarlo.","I’ll try it again."],["No vuelvo a comer aquí.","I won’t eat here again."],["¿Me lo vuelves a decir?","Can you tell me again?"]]},
  {es:"Dejé de…",       en:"I stopped (doing)…",    ex:[["Dejé de tomar café.","I stopped drinking coffee."],["Dejó de llover.","It stopped raining."],["No dejes de practicar.","Don’t stop practicing."]]},
  {es:"¿Te importa si…?", en:"Do you mind if…?",    ex:[["¿Te importa si abro la ventana?","Do you mind if I open the window?"],["¿Le importa si me siento aquí?","Do you mind if I sit here?"],["¿Te importa si llego tarde?","Do you mind if I arrive late?"]]},
  {es:"Espero que…",    en:"I hope that…",          ex:[["Espero que estés bien.","I hope you’re well."],["Espero que venga.","I hope she comes."],["Espero que te guste.","I hope you like it."]]},
  {es:"Creo que…",      en:"I think that…",         ex:[["Creo que sí.","I think so."],["Creo que va a llover.","I think it’s going to rain."],["No creo que venga.","I don’t think he’s coming."]]}
];

var CONNECTOR_GROUPS = [
  {k:"add",   name:"Adding"},
  {k:"but",   name:"Contrast"},
  {k:"why",   name:"Cause and result"},
  {k:"order", name:"Order and time"},
  {k:"talk",  name:"In conversation"}
];
var CONNECTORS = [
  ["add","y","and","Tengo un hermano y una hermana.","I have a brother and a sister.","Becomes e before an i- sound: padre e hijo."],
  ["add","también","also, too","Yo también quiero ir.","I want to go too.",""],
  ["add","tampoco","neither, not either","Yo tampoco sé.","I don’t know either.","The negative of también."],
  ["add","además","besides, also","Además, es barato.","Besides, it’s cheap.",""],
  ["add","incluso","even","Incluso los niños lo saben.","Even the kids know it.",""],
  ["add","ni… ni…","neither… nor…","No quiero ni té ni café.","I want neither tea nor coffee.",""],
  ["but","pero","but","Es caro, pero es bueno.","It’s expensive, but it’s good.",""],
  ["but","sino","but rather","No es azul, sino verde.","It isn’t blue, but green.","After a negative, to correct it."],
  ["but","aunque","although, even though","Aunque llueve, vamos a salir.","Although it’s raining, we’re going out.",""],
  ["but","sin embargo","however","Sin embargo, no dijo nada.","However, he said nothing.",""],
  ["but","en cambio","on the other hand","Yo prefiero el mar; mi hermana, en cambio, la montaña.","I prefer the sea; my sister, on the other hand, the mountains.",""],
  ["but","a pesar de","in spite of","A pesar de la lluvia, vinieron.","In spite of the rain, they came.",""],
  ["why","porque","because","No fui porque estaba enferma.","I didn’t go because I was sick.",""],
  ["why","como","since (at the start)","Como no tenía dinero, no compré nada.","Since I had no money, I didn’t buy anything.","Starts the sentence; porque comes in the middle."],
  ["why","por eso","that’s why","Estaba cansad{o|a}, por eso me acosté.","I was tired, that’s why I went to bed.",""],
  ["why","así que","so","Llueve, así que me quedo en casa.","It’s raining, so I’m staying home.",""],
  ["why","entonces","so, then","Entonces, ¿vienes o no?","So, are you coming or not?",""],
  ["why","para que","so that","Te lo digo para que lo sepas.","I’m telling you so that you know.","Always followed by the subjunctive."],
  ["order","primero","first","Primero, lavamos las manos.","First, we wash our hands.",""],
  ["order","luego","then, later","Luego vamos al parque.","Then we go to the park.",""],
  ["order","después de","after","Después de comer, descanso.","After eating, I rest.","Takes an infinitive: después de comer."],
  ["order","antes de","before","Antes de salir, llámame.","Before leaving, call me.",""],
  ["order","mientras","while","Escucho música mientras cocino.","I listen to music while I cook.",""],
  ["order","cuando","when","Cuando llego a casa, ceno.","When I get home, I have dinner.",""],
  ["order","por fin","at last, finally","¡Por fin llegaste!","You finally arrived!",""],
  ["talk","la verdad es que","the truth is","La verdad es que no me gusta.","The truth is I don’t like it.",""],
  ["talk","en realidad","actually","En realidad, soy de Chile.","Actually, I’m from Chile.",""],
  ["talk","por ejemplo","for example","Me gustan las frutas, por ejemplo, el mango.","I like fruit, for example, mango.",""],
  ["talk","o sea","I mean, in other words","Llego a las ocho, o sea, en una hora.","I arrive at eight, I mean, in an hour.",""],
  ["talk","de todos modos","anyway","De todos modos, gracias.","Thanks anyway.",""],
  ["talk","por lo menos","at least","Por lo menos llegamos a tiempo.","At least we arrived on time.",""]
];

/* You speak the "b" lines. A line in [brackets] in the English is a hint for what to say. */
var DIALOGUES = [
 {k:"meet", title:"Meeting someone", where:"At a church lunch", lines:[
  ["a","¡Hola! ¿Cómo te llamas?","Hi! What’s your name?"],
  ["b","Hola, me llamo Sara. ¿Y tú?","Hi, my name is Sara. And you?"],
  ["a","Me llamo Daniel. Mucho gusto.","My name is Daniel. Nice to meet you."],
  ["b","Igualmente. ¿De dónde eres?","Likewise. Where are you from?"],
  ["a","Soy de la República Dominicana. ¿Y tú?","I’m from the Dominican Republic. And you?"],
  ["b","Soy de Ohio. Estoy aprendiendo español.","I’m from Ohio. I’m learning Spanish."],
  ["a","¡Qué bien! Hablas muy bien.","How great! You speak very well."],
  ["b","Gracias, pero todavía hablo un poco despacio.","Thanks, but I still speak a little slowly."]]},
 {k:"cafe", title:"Ordering at a café", where:"A small café", lines:[
  ["a","Buenos días. ¿Qué le sirvo?","Good morning. What can I get you?"],
  ["b","Buenos días. Quisiera un café con leche, por favor.","Good morning. I’d like a coffee with milk, please."],
  ["a","¿Grande o pequeño?","Large or small?"],
  ["b","Pequeño, por favor. ¿Tienen pan dulce?","Small, please. Do you have sweet bread?"],
  ["a","Sí, tenemos conchas y cuernitos.","Yes, we have conchas and croissants."],
  ["b","Una concha, por favor. ¿Cuánto es?","One concha, please. How much is it?"],
  ["a","Son cuatro dólares.","That’s four dollars."],
  ["b","Aquí tiene. Muchas gracias.","Here you go. Thank you very much."]]},
 {k:"directions", title:"Asking for directions", where:"On the street", lines:[
  ["b","Perdón, ¿dónde está la farmacia?","Excuse me, where is the pharmacy?"],
  ["a","Siga derecho dos cuadras y luego gire a la izquierda.","Go straight two blocks and then turn left."],
  ["b","¿Está lejos?","Is it far?"],
  ["a","No, está muy cerca. Cinco minutos a pie.","No, it’s very close. Five minutes on foot."],
  ["b","¿Puede repetir, por favor? Más despacio.","Can you repeat, please? More slowly."],
  ["a","Claro. Dos cuadras derecho, y a la izquierda.","Of course. Two blocks straight, and to the left."],
  ["b","Ah, ya entiendo. Muchas gracias.","Oh, now I understand. Thank you very much."],
  ["a","De nada. Que le vaya bien.","You’re welcome. Have a good day."]]},
 {k:"family", title:"Talking about family", where:"With a new friend", lines:[
  ["a","¿Tienes hermanos?","Do you have brothers and sisters?"],
  ["b","Sí, tengo un hermano y dos hermanas.","Yes, I have a brother and two sisters."],
  ["a","¿Son mayores o menores que tú?","Are they older or younger than you?"],
  ["b","Mi hermano es mayor. Mis hermanas son menores.","My brother is older. My sisters are younger."],
  ["a","¿Y dónde vive tu familia?","And where does your family live?"],
  ["b","Mis padres viven en Ohio, cerca de mí.","My parents live in Ohio, near me."],
  ["a","¡Qué bueno! ¿Los ves mucho?","That’s great! Do you see them a lot?"],
  ["b","Sí, voy a su casa casi todos los domingos.","Yes, I go to their house almost every Sunday."]]},
 {k:"weekend", title:"What did you do?", where:"Monday morning", lines:[
  ["a","¿Qué hiciste el fin de semana?","What did you do over the weekend?"],
  ["b","El sábado fui al parque con unas amigas.","On Saturday I went to the park with some friends."],
  ["a","¡Qué divertido! ¿Y el domingo?","How fun! And on Sunday?"],
  ["b","El domingo fui a la iglesia y después comí con mi familia.","On Sunday I went to church and afterwards I ate with my family."],
  ["a","¿Qué comieron?","What did you all eat?"],
  ["b","Mi mamá hizo pollo con arroz. Estuvo delicioso.","My mom made chicken and rice. It was delicious."],
  ["a","Yo no hice nada. Dormí mucho.","I didn’t do anything. I slept a lot."],
  ["b","¡A veces eso es lo mejor!","Sometimes that’s the best thing!"]]},
 {k:"plans", title:"Making plans", where:"On the phone", lines:[
  ["a","¿Qué vas a hacer mañana?","What are you going to do tomorrow?"],
  ["b","Voy a estudiar por la mañana. ¿Por qué?","I’m going to study in the morning. Why?"],
  ["a","¿Quieres ir al cine por la tarde?","Do you want to go to the movies in the afternoon?"],
  ["b","¡Sí, me encantaría! ¿A qué hora?","Yes, I’d love to! At what time?"],
  ["a","A las cuatro. ¿Te parece bien?","At four. Does that sound good?"],
  ["b","Perfecto. ¿Dónde nos vemos?","Perfect. Where shall we meet?"],
  ["a","En la entrada del cine.","At the entrance of the theater."],
  ["b","Muy bien. Hasta mañana.","Very good. See you tomorrow."]]},
 {k:"doctor", title:"At the doctor", where:"A clinic", lines:[
  ["a","Buenas tardes. ¿Qué le pasa?","Good afternoon. What’s wrong?"],
  ["b","Me duele mucho la cabeza y tengo fiebre.","My head hurts a lot and I have a fever."],
  ["a","¿Desde cuándo se siente así?","Since when have you felt like this?"],
  ["b","Desde ayer por la noche.","Since last night."],
  ["a","¿Toma alguna medicina?","Are you taking any medicine?"],
  ["b","No, no tomo nada. ¿Es algo grave?","No, I’m not taking anything. Is it something serious?"],
  ["a","No se preocupe. Es un resfriado. Descanse y tome mucha agua.","Don’t worry. It’s a cold. Rest and drink a lot of water."],
  ["b","Muy bien. Muchas gracias, doctor.","Very well. Thank you very much, doctor."]]},
 {k:"shop", title:"Shopping for clothes", where:"A clothing store", lines:[
  ["a","Hola, ¿en qué puedo servirle?","Hi, how can I help you?"],
  ["b","Sí, busco una chaqueta para el invierno.","Yes, I’m looking for a jacket for the winter."],
  ["a","¿Qué talla usa?","What size do you wear?"],
  ["b","Uso la talla mediana. ¿La tiene en azul?","I wear a medium. Do you have it in blue?"],
  ["a","Sí, aquí tiene. El probador está allí.","Yes, here you go. The fitting room is over there."],
  ["b","Me queda un poco grande. ¿Tiene una más pequeña?","It’s a bit big on me. Do you have a smaller one?"],
  ["a","Claro. Esta es la pequeña.","Of course. This is the small one."],
  ["b","Esta me queda perfecta. Me la llevo.","This one fits perfectly. I’ll take it."]]},
 {k:"restaurant", title:"At a restaurant", where:"Dinner out", lines:[
  ["a","Buenas noches. ¿Ya saben qué van a pedir?","Good evening. Do you know what you’ll order?"],
  ["b","Sí. Para mí, la sopa de pollo, por favor.","Yes. For me, the chicken soup, please."],
  ["a","¿Y para tomar?","And to drink?"],
  ["b","Un vaso de agua sin hielo, por favor.","A glass of water without ice, please."],
  ["a","¿Algo más?","Anything else?"],
  ["b","No, gracias. Eso es todo por ahora.","No, thanks. That’s all for now."],
  ["a","¿Todo bien con la comida?","Is everything good with the food?"],
  ["b","Sí, está riquísima. ¿Nos trae la cuenta, por favor?","Yes, it’s delicious. Could you bring us the check, please?"]]},
 {k:"childhood", title:"When I was little", where:"Sharing stories", lines:[
  ["a","¿Dónde vivías cuando eras niñ{o|a}?","Where did you live when you were a {boy|girl}?"],
  ["b","Vivía en un pueblo pequeño cerca de un lago.","I lived in a small town near a lake."],
  ["a","¿Y qué hacías en el verano?","And what did you do in the summer?"],
  ["b","Nadaba todos los días y jugaba con mis primos.","I swam every day and played with my cousins."],
  ["a","¡Qué bonito! ¿Tenías una mascota?","How lovely! Did you have a pet?"],
  ["b","Sí, teníamos un perro que se llamaba Max.","Yes, we had a dog named Max."],
  ["a","¿Todavía vas a ese pueblo?","Do you still go to that town?"],
  ["b","A veces. Siempre me trae muy buenos recuerdos.","Sometimes. It always brings back very good memories."]]}
];
